[project]
name = "project-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "numpy>=2.0.2",
    "pandas>=2.2.3",
    "matplotlib>=3.9.2",
    "seaborn>=0.13.2",
    "jupyter>=1.1.1",
    "ipykernel>=6.29.5",
<<<<<<< HEAD
    "openpyxl>=3.1.5",
    "update>=0.0.1",
=======
    "plotly>=5.24.1",
>>>>>>> d1cd93eccea16a69a39d0b22497d99cf50c5a1de
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
